# -*- mode: ruby -*-
# vi: set ft=ruby :

# load the configuration
require 'yaml'
conf = YAML.load_file 'config/config.yml'
config_path = conf['global']['config_path']
host_static_ip = conf['global']['host_static_ip']
kafka_topics = conf['kafka']['topics']
log_mnt_path = conf['global']['log_mnt_path']
currentDir = File.expand_path File.dirname(__FILE__)

ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.6.0"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.synced_folder '.', '/vagrant'

# config.vm.define "mongodb" do |node|
#   node.vm.provider "docker" do |d|
#     d.name = "bigboost-mongodb"
#     d.image = "droyuki/bigboost-mongodb:v1"
#     d.volumes = ["#{log_mnt_path}:/opt/data", "#{config_path}/mongodb:/opt/mongodb/conf", "#{currentDir}/NAS:/NAS", "/vagrant/BigBoost:/opt/BigBoost", "/etc/localtime:/etc/localtime:ro", "/Racademy:/opt/Racademy"]
#   end
#   node.vm.hostname = "bigboost-mongodb"
#   node.ssh.username = "root"
#   node.ssh.port = "22"
#end

config.vm.define "mysql" do |node|
    node.vm.provider "docker" do |d| 
      d.name = "bigboost-mysql"
      d.image = "droyuki/bigboost-mysql:v1"
      d.ports = ["3306:3306"]
      d.volumes = ["#{log_mnt_path}:/opt/data", "#{currentDir}/NAS:/NAS","/vagrant/BigBoost:/opt/BigBoost", "/etc/localtime:/etc/localtime:ro"]
    end 
    node.vm.hostname = "bigboost-mysql"
    node.ssh.username = "root"
    node.ssh.port = "22"
  end 

config.vm.define "kafka" do |node|
    node.vm.provider "docker" do |d| 
      d.name = "bigboost-kafka"
      d.image = "droyuki/bigboost-kafka:v1"
      d.ports = ["2181:2181","9092:9092"]
      d.volumes = ["#{log_mnt_path}:/opt/data", "#{config_path}/kafka:/opt/kafka/config", "#{currentDir}/NAS:/NAS","/vagrant/BigBoost:/opt/BigBoost", "/etc/localtime:/etc/localtime:ro"]
      d.cmd = ["start_kafka.sh", "-t", kafka_topics, "-hoip", host_static_ip]
    end 
    node.vm.hostname = "bigboost-kafka"
    node.ssh.username = "root"
    node.ssh.port = "22"
  end 

 config.vm.define "spark" do |node|
    node.vm.provider "docker" do |d|
      d.name = "bigboost-spark"
      d.image = "droyuki/bigboost-spark:lab-v1"
      d.ports = ["5555:8080","4040:4040","8081:8081","4042:4042","7077:7077", "4041:4041", "19999:9999", "50070:50070", "9001:9001", "8888:8888"]
      d.volumes = ["#{log_mnt_path}:/opt/data", "#{config_path}/spark:/opt/spark/conf", "#{currentDir}/NAS:/NAS", "/vagrant/BigBoost:/opt/BigBoost", "/etc/localtime:/etc/localtime:ro", "/Racademy:/opt/Racademy"]
      d.create_args = ["--memory", "6g"]
      d.link("bigboost-mysql:bigboost-mysql")
      d.link("bigboost-kafka:bigboost-kafka")
      d.env = {
        "LANG"=>"C.UTF-8"
      }
      d.cmd = ["start-spark.sh"]
    end
    node.vm.hostname = "bigboost-spark"
    node.ssh.username = "root"
    node.ssh.port = "22"
  end

   config.vm.define "sparkWorker3" do |node|
    node.vm.provider "docker" do |d|
      d.name = "bigboost-sparkWorker3"
      d.image = "droyuki/bigboost-spark:lab-v1"
      d.ports = ["35555:8080","34040:4040","38081:8081","34042:4042","37077:7077", "34041:4041", "49000:9000"]
      d.volumes = ["#{log_mnt_path}:/opt/data", "#{config_path}/spark:/opt/spark/conf", "#{currentDir}/NAS:/NAS", "/vagrant/BigBoost:/opt/BigBoost", "/etc/localtime:/etc/localtime:ro"]
      #d.create_args = ["--volumes-from", "bigboost-kafka"]
      d.create_args = ["--memory", "6g"]
      d.link("bigboost-spark:bigboost-spark")
      d.link("bigboost-mysql:bigboost-mysql")
      d.link("bigboost-kafka:bigboost-kafka")
      d.env = {
        "LANG"=>"C.UTF-8"
      }
      d.cmd = ["start-sparkWorker.sh"]
    end
    node.vm.hostname = "bigboost-sparkWorker3"
    node.ssh.username = "root"
    node.ssh.port = "22"
  end

   config.vm.define "sparkWorker2" do |node|
    node.vm.provider "docker" do |d|
      d.name = "bigboost-sparkWorker2"
      d.image = "droyuki/bigboost-spark:lab-v1"
      d.ports = ["25555:8080","24040:4040","28081:8081","24042:4042","27077:7077", "24041:4041", "39000:9000"]
      d.volumes = ["#{log_mnt_path}:/opt/data", "#{config_path}/spark:/opt/spark/conf", "#{currentDir}/NAS:/NAS", "/vagrant/BigBoost:/opt/BigBoost", "/etc/localtime:/etc/localtime:ro"]
      d.create_args = ["--memory", "6g"]
      d.link("bigboost-spark:bigboost-spark")
      d.link("bigboost-mysql:bigboost-mysql")
      d.link("bigboost-kafka:bigboost-kafka")
      d.env = {
        "LANG"=>"C.UTF-8"
      }
      d.cmd = ["start-sparkWorker.sh"]
    end
    node.vm.hostname = "bigboost-sparkWorker2"
    node.ssh.username = "root"
    node.ssh.port = "22"
  end

   config.vm.define "sparkWorker" do |node|
    node.vm.provider "docker" do |d|
      d.name = "bigboost-sparkWorker"
      d.image = "droyuki/bigboost-spark:lab-v1"
      d.create_args = ["--memory", "6g"]
      d.link("bigboost-kafka:bigboost-kafka")
      d.link("bigboost-spark:bigboost-spark")
      d.link("bigboost-mysql:bigboost-mysql")
      d.link("bigboost-sparkWorker2:bigboost-sparkWorker2")
      d.link("bigboost-sparkWorker3:bigboost-sparkWorker3")
      d.ports = ["15555:8080","14040:4040","18081:8081","14042:4042","17077:7077", "14041:4041", "29000:9000"]
      d.volumes = ["#{log_mnt_path}:/opt/data", "#{config_path}/spark:/opt/spark/conf", "#{currentDir}/NAS:/NAS", "/vagrant/BigBoost:/opt/BigBoost", "/etc/localtime:/etc/localtime:ro"]
      d.env = {
        "LANG"=>"C.UTF-8"
      }
      d.cmd = ["start-sparkWorker.sh"]
    end
    node.vm.hostname = "bigboost-sparkWorker"
    node.ssh.username = "root"
    node.ssh.port = "22"
  end

end
