# -*- mode: ruby -*-
# vi: set ft=ruby :

# load the configuration
require 'yaml'
conf = YAML.load_file 'config/config.yml'
config_path = conf['global']['config_path']
host_static_ip = conf['global']['host_static_ip']
kafka_topics = conf['kafka']['topics']
log_mnt_path = conf['global']['log_mnt_path']
currentDir = File.expand_path File.dirname(__FILE__)

ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.6.0"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.synced_folder '.', '/vagrant'

 config.vm.define "mongodb" do |node|
   node.vm.provider "docker" do |d|
     d.name = "bigboost-mongodb"
     d.image = "droyuki/bigboost-mongodb:v1"
     d.volumes = ["#{log_mnt_path}:/opt/data", "#{config_path}/mongodb:/opt/mongodb/conf", "#{currentDir}/NAS:/NAS", "/vagrant/BigBoost:/opt/BigBoost", "/etc/localtime:/etc/localtime:ro", "/Racademy:/opt/Racademy"]
   end
   node.vm.hostname = "bigboost-mongodb"
   node.ssh.username = "root"
   node.ssh.port = "22"
end

config.vm.define "kafka" do |node|
    node.vm.provider "docker" do |d| 
      d.name = "bigboost-kafka"
      d.image = "droyuki/bigboost-kafka:v1"
      d.ports = ["2181:2181","9092:9092"]
      d.volumes = ["#{log_mnt_path}:/opt/data", "#{config_path}/kafka:/opt/kafka/config", "#{currentDir}/NAS:/NAS","/vagrant/BigBoost:/opt/BigBoost", "/etc/localtime:/etc/localtime:ro"]
      d.cmd = ["start_kafka.sh", "-t", kafka_topics, "-hoip", host_static_ip]
    end 
    node.vm.hostname = "bigboost-kafka"
    node.ssh.username = "root"
    node.ssh.port = "22"
  end 

 config.vm.define "spark" do |node|
    node.vm.provider "docker" do |d|
      d.name = "bigboost-spark"
      d.image = "droyuki/bigboost-spark:v5"
     # d.link("bigboost-mongodb:bigboost-mongodb")
      d.ports = ["5555:8080","4040:4040","8081:8081","4042:4042","7077:7077", "4041:4041", "19000:9000", "50070:50070"]
      d.volumes = ["#{log_mnt_path}:/opt/data", "#{config_path}/spark:/opt/spark/conf", "#{currentDir}/NAS:/NAS", "/vagrant/BigBoost:/opt/BigBoost", "/etc/localtime:/etc/localtime:ro", "/Racademy:/opt/Racademy"]
      #d.create_args = ["--volumes-from", "bigboost-kafka"]
      d.env = {
        "LANG"=>"C.UTF-8"
      }
      d.cmd = ["start-spark.sh"]
    end
    node.vm.hostname = "bigboost-spark"
    node.ssh.username = "root"
    node.ssh.port = "22"
  end

   config.vm.define "sparkWorker" do |node|
    node.vm.provider "docker" do |d|
      d.name = "bigboost-sparkWorker"
      d.image = "droyuki/bigboost-spark:v5"
     # d.link("bigboost-mongodb:bigboost-mongodb")
      d.link("bigboost-kafka:bigboost-kafka")
      d.link("bigboost-spark:bigboost-spark")
      d.ports = ["15555:8080","14040:4040","18081:8081","14042:4042","17077:7077", "14041:4041"]
      d.volumes = ["#{log_mnt_path}:/opt/data", "#{config_path}/spark:/opt/spark/conf", "#{currentDir}/NAS:/NAS", "/vagrant/BigBoost:/opt/BigBoost", "/etc/localtime:/etc/localtime:ro"]
      #d.create_args = ["--volumes-from", "bigboost-kafka"]
      d.env = {
        "LANG"=>"C.UTF-8"
      }
      d.cmd = ["start-sparkWorker.sh"]
    end
    node.vm.hostname = "bigboost-sparkWorker"
    node.ssh.username = "root"
    node.ssh.port = "22"
  end

end
